### ISSUE TITLE
There seems to be a issue

### ISSUE THREAD

**Issue by cooolg** [RedstoneDubstep/Vanishmod#28] opened 2024-06-04 17:59 UTC
![image](https://github.com/RedstoneDubstep/Vanishmod/assets/137922684/22e0934b-f5d8-402b-a6ea-e91ac1a603f1)
It still shows me hidden in the multiplayer list

**Comment by RedstoneDubstep** [comment] 2024-06-05 05:56
Hello, configs and config value changes behave weirdly on Forge/NeoForge, so they only reliably apply when the config is changed while the server is offline. Have you tried that? If so and the problem persists, what Minecraft and Vanishmod versions are you using?

**Comment by cooolg** [comment] 2024-06-05 10:14
Well, Am using Minecraft version 1.19.2 And am using 1.1.15 jar I have made the server offline yet it still doesnt work, But I am using essential

**Comment by RedstoneDubstep** [comment] 2024-06-05 14:02
Hello, I tried to reproduce this with only Vanishmod on 1.19.2 on a local server (the config option is already disabled on the server) and, as you can see on the screenshot, I'm not hidden from the multiplayer screen player list even though I'm vanished. This might be a conflict with Essentials, however since I'm no longer actively developing for Minecraft 1.19.2, I'm afraid I can't look into this further. Therefore, I will close this issue.

![image](https://github.com/RedstoneDubstep/Vanishmod/assets/42962686/d2072612-4703-4523-ac7e-40ad1520cfb0)

**Closed as completed by RedstoneDubstep** 2024-06-05 14:02 UTC
