### ISSUE TITLE
Servercrash with CrateLib and Gameversion 1.21

### ISSUE THREAD

**Issue by bomber1992** [RedstoneDubstep/Vanishmod#32] opened 2024-07-23 06:33 UTC
[crash-2024-07-22_23.07.57-fml.txt](https://github.com/user-attachments/files/16344604/crash-2024-07-22_23.07.57-fml.txt)

**Comment by RedstoneDubstep** [comment] 2024-07-23 09:15
Hello, thanks for reporting! From what I've gathered from the crash report, I believe the cause of this crash is (in this case) CraterLib, since it tries to handle Vanishmod's `PlayerVanishEvent` like a mod bus event instead of a regular game bus one. @hypherionmc (hope it's fine to consult you here) can you confirm this, or am I on the wrong train of thought?

**Comment by bomber1992** [comment] 2024-07-23 09:36
Yes, that's exactly where the error lies. As soon as I start it without CraterLib, it works without problems, but unfortunately I need this mod because I use a modpack :)

**Comment by hypherionmc** [comment] 2024-07-23 15:52
Known issue from our side. Has been fixed in a development version already. Just doing some final stuff before releasing. This does also affect our 1.20.4 version of NeoForge. No idea how the heck it slipped through testing, but it did :disappointed: 

https://nightbloom.cc/project/craterlib/files/4td647ev if you need it badly :smile: 

(We literally discovered this issue last night during some tests)

**Comment by RedstoneDubstep** [comment] 2024-07-23 16:12
Ah alright, sounds good! I'll close this issue then since CraterLib already contains the fix (which is gonna be officially released soon).

**Closed as completed by RedstoneDubstep** 2024-07-23 16:12 UTC
