### ISSUE TITLE
Player display issue

### ISSUE THREAD

**Issue by oSecret** [RedstoneDubstep/Vanishmod#14] opened 2023-06-20 19:40 UTC
While having the vanish mod on my VaultHunters server my displayed players never go over 12. 
![Screenshot_142](https://github.com/RedstoneDubstep/Vanishmod/assets/128076413/cdc83079-a8bc-40fe-aeba-4c276a9feb85)
![Screenshot_143](https://github.com/RedstoneDubstep/Vanishmod/assets/128076413/0eeaf18d-7d06-4e47-a03e-a158588ff278)

**Comment by RedstoneDubstep** [comment] 2023-06-20 19:42
Hello, I assume all of the 19 players online are not vanished? Also, what version of Forge and the Vanishmod are you using?

**Comment by oSecret** [comment] 2023-06-20 23:12
Correct, no one was vanished 
Vanishmod-1.18.2-1.1.10
Forge-1.18.2-40.2.1 
although I had the same issue a while ago with a previous forge version.

**Comment by RedstoneDubstep** [comment] 2023-06-21 08:52
Does the modlist your server is using contain any extra mods/misses any mods compared to the modlist of the "Vault Hunter 3rd Edition" modpack on CurseForge, other than that the Vanishmod is installed?

**Comment by oSecret** [comment] 2023-06-21 14:58
Extra mods: 
alternate-current-mc1.18-1.2.1
block_log-1.0.0+1.18.2
canary-mc1.18.2-0.1.8
Chunky-1.2.164
dcintegration-forge-2.5.0-1.18.2
flan-1.18.2-1.8.2-forge
ftb-essentials-1802.1.7-build.42
itemblacklist-1.18.2-1.2.3
lazydfu-0.1.2
logprot-1.18.2-1.6
LuckPerms-Forge-5.4.26
ModListObserver-1.18.2-1.0.1
pluto-mc1.18.2-0.0.6
quickspawns-1.18.2-1.0.3-forge
saturn-mc1.16.5-0.0.3
starlight-1.0.2+forge.546ae87
starterkit_1.18.2-3.9
Tempban-1.18-1.0.1

Missing: 
FTBBackups

**Comment by RedstoneDubstep** [comment] 2023-06-21 20:31
I'm afraid to say that I currently do not have the computing capacity to run a Vault Hunters server + client(s) to at least try to reproduce this issue, so this might take a while for me to properly resolve. I might be getting a better PC in the future, in the meantime it would be incredibly helpful if you
1. could test whether this issue also arises if the Vanishmod server config option `hidePlayersFromPlayerLists` is set to false
2. could test whether this issue arises with only Vanishmod installed, and if not, do a binary search (= remove half of your mods, see if the issue is present, if yes -> test with half of current mods, if not -> test with unused mods) to find out which mod(s) cause this incompatibility (if it even is one).

Thanks a lot in advance, and sorry that this issue might not get resolved as quickly as expected.

**Comment by Mareron** [comment] 2023-06-26 08:20
We've experienced the same issue but did find a fix.
In /world/serverconfig/ you'll find a vanishmod-server.toml file

In there you can set 
#Should vanished players be hidden from player lists such as the /list command and the list in the Multiplayer screen?
hidePlayersFromPlayerLists = false

that fixed the issue for us

**Comment by Mareron** [comment] 2023-06-26 16:13
It was also stuck at 12, yes.
We are using a different set of mods.
Pixelmon and Oh the Biomes you'll go and a whole bunch of utility/content plugins

**Comment by RedstoneDubstep** [comment] 2023-06-26 19:48
Fixed by https://github.com/RedstoneDubstep/Vanishmod/commit/be9fb691c4a0ffd87af23ae64d4e52a019be9ed5, new version will be released in a bit

**Closed by RedstoneDubstep** 2023-06-26 19:48 UTC
