### ISSUE TITLE
Vanshing and Leaving causes a server internal error

### ISSUE THREAD

**Issue by ANONYMOUS6010** [RedstoneDubstep/Vanishmod#9] opened 2022-03-17 16:44 UTC
So the vanish works perfectly since we last talked, but whenever an admin or I leave the server while vanished, and the server restarts, when i try to log back in, I get a server internal error. I can't log in unless I delete my UUID from the player list, which resets me as a new player. There is no crash log bc nothing crashes. 

Side thing, if you manage to fix this issue, can you make it a feature where you can leave while vanished, and it doesn't say a leave message?

**Comment by RedstoneDubstep** [comment] 2022-03-17 17:20
Hi, nice to hear that you had a generally positive experience with the mod! 
Regarding your issue, please provide the server log of the internal exception (the server logs should be in the `logs` folder, usually the `lastest.log` should contain the full stacktrace), that would make it easier to figure out the issue. I assume that this is a case of mod incompatibility again, because in my testing (Minecraft 1.16.5, Forge 36.2.28, Vanishmod v1.1.3.1) the mentioned issue didn't occur to me, so the mod list would probably also be helpful.
As for your leave message note, it should be the case that no join/leave message gets sent when you're leaving the server while being vanished (and, in my testing, this was actually the case), so the described behaviour you experienced would be a bug (and, I assume, another mod incompatibility).

**Comment by ANONYMOUS6010** [comment] 2022-03-17 18:14
[crash-2022-03-16_20.17.08-server.txt](https://github.com/RedstoneDubstep/Vanishmod/files/8288811/crash-2022-03-16_20.17.08-server.txt)
this is the server's latest log, this should not be the issue because the mod that crashed the sever was patched with an updates version, 
[crash-2022-03-17_12.36.31-client.txt](https://github.com/RedstoneDubstep/Vanishmod/files/8288964/crash-2022-03-17_12.36.31-client.txt)

And this is my lastest crash log on my pc.

**Comment by ANONYMOUS6010** [comment] 2022-03-17 18:17
We do use a discord intergrated chat bot, so all messages from in games also appear on the discord server. The leave message was a miscommunication on my part. We use a discord bot to relay the messages from in game to the discord server. When I vanish it doesn't say I left on the discord. I'm pretty sure you might not be able to fix that bc its not the mod that controls that but sorry yet again.

**Comment by RedstoneDubstep** [comment] 2022-03-17 18:59
The crash reports you sent me are, as you said, from an unrelated crash and thus not helpful at all. What I probably need is the `latest.log`, which, again, can be found in the `logs` folder (which is in the same place as the `crash-reports` folder you got the server crash reports from). 
Also, out of curiosity, from where did you get the notification that you got an internal server error (like, where was text/notification printed)? And if you don't host your server yourself, where/through what service do you host it?

And regarding your message about the discord bot, what mod do you use to relay the messages to Discord? I might be able to add compatibility for it (as I've already done for the similar mod minecraft2discord), but I need to look into it

**Comment by ANONYMOUS6010** [comment] 2022-03-18 14:50
I got the message on the Minecraft screen, as a reason why I can't log in. it says, 'Server Internal Error'.  As for the host we use, we use Apex Hosting. 
[latest (2).log](https://github.com/RedstoneDubstep/Vanishmod/files/8305328/latest.2.log)

The discord mod is https://www.curseforge.com/minecraft/mc-mods/dcintegration

**Comment by RedstoneDubstep** [comment] 2022-03-19 17:36
The log unfortunately didn't include any obvious hints, so it'd be helpful if you could send 1. the mod list the server is using (so I can reproduce the issue more easily) or 2. the `debug.log` (which should be in the same folder as the `latest.log` and which might include more info about the Server Internal Error). Also, in the log you gave me, which player was the one that was unable to join the server? (That info would be nice to know for the `debug.log` as well, should you send it to me).

**Comment by ANONYMOUS6010** [comment] 2022-03-19 22:08
Yeah so i ran some tests, and when I leave the server while vanished, and the server restarts, I cannot join. I get in by going into the world/data folder and deleting all of my player data associated with the server. I basically join again as a new player. 
The modlist can be found at https://www.curseforge.com/minecraft/modpacks/helrims-fable-modpack
We are still on forge version 36.2.20, and on Minecraft 1.16.5
[debug.log](https://github.com/RedstoneDubstep/Vanishmod/files/8310218/debug.log)
[latest (3).log](https://github.com/RedstoneDubstep/Vanishmod/files/8310219/latest.3.log)
These logs are from right now as I am typing, hope these help

**Comment by ANONYMOUS6010** [comment] 2022-03-24 19:33
Any updates?

**Comment by RedstoneDubstep** [comment] 2022-03-24 19:39
Yes, I should have been able to fix the issue in one of the last commits (I changed a lot of code revolving around the underlying issue, so there may be multiple commits involved), however I'm haven't released a new version yet because I wanted to test some other stuff that I've worked on in this version. If everything runs well, you can expect the release of the new version next week or so.

**Comment by ANONYMOUS6010** [comment] 2022-03-24 19:40
kk, thanks so much bro

**Comment by RedstoneDubstep** [comment] 2022-04-04 06:00
Were you able to test the new version of the Vanishmod with your modpack? If yes, I'd be curious whether it fixed your loading problem (so I can close this issue)

**Comment by RedstoneDubstep** [comment] 2022-04-15 17:03
Since I haven't received further comments, I am going to assume this issue has been fixed. If it hasn't been and the problem is still there, feel free to reopen this issue.

**Closed as completed by RedstoneDubstep** 2022-04-15 17:03 UTC
