### ISSUE TITLE
[1.16.5] Server hangs upon a player attempting to join

### ISSUE THREAD

**Issue by ghost** [RedstoneDubstep/Vanishmod#10] opened 2022-09-07 05:40 UTC
Whenever attempting to join a Forge server using the latest 1.16.5 version of Vanishmod, the server hangs due to an incompatibility with the player join handler (resulting in a crash). I've attached a crash log so that the issue can be analyzed and resolved.

The incompatibility seems to be with Elenai Dodge 2, but I have a feeling it may affect other mods as well.

[crash-2022-09-07_06.26.12-server.txt](https://github.com/RedstoneDubstep/Vanishmod/files/9502973/crash-2022-09-07_06.26.12-server.txt)

**Comment by RedstoneDubstep** [comment] 2022-09-07 11:14
Hello,
firstly, I don't support 1.16.5 anymore for my mods, which means that I'll only release another 1.16.5 Vanishmod version if a critical issue occurs.
Secondly, I cannot reproduce that crash (or a severe server hang) with Vanishmod v1.1.6 and ElenaiDodge2 1.1.0. I saw that you were using other mods as well when the crash report was generated, so this might be an issue resulting from the combination of several mods, or just from the game taking that long to load chunks around a joining player. If you want, you can do a binary search to figure out which mods cause the game to stall and crash.

**Comment by RedstoneDubstep** [comment] 2022-09-26 11:55
Closing this as not reproducible, if any more information is available feel free to reopen this issue.

**Closed as not planned by RedstoneDubstep** 2022-09-26 11:55 UTC
