### ISSUE TITLE
Incompatability with Aether Mod

### ISSUE THREAD

**Issue by Mikeatron-User** [RedstoneDubstep/Vanishmod#26] opened 2024-02-07 06:42 UTC
Log: https://mclo.gs/MZ4xNyu

The sound suppression system does not like moas from Aether.

**Comment by RedstoneDubstep** [comment] 2024-02-07 09:32
Duplicate of (the also just recently opened) issue #25.

**Closed as not planned by RedstoneDubstep** 2024-02-07 09:32 UTC
